markdown: kramdown
highlighter: rouge
permalink: /blog/:title
title: "WOR(L)DS"
date: Jun 5-7
year: 2019
tickets: true
tickets-eb: //eventbrite.com/tickets-external?eid=49969466018&ref=etckt
tickets-eb-link: http://kerning-2019.eventbrite.com
tickets-eb-height: 500px
speakers: false
talks: false
workshops: false
schedule: false
cfs: true
rdiscount:
  extensions: [smart]
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
